/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Page2IndexRouteImport } from './routes/page-2/index'
import { Route as AnotherPageIndexRouteImport } from './routes/another-page/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Page2IndexRoute = Page2IndexRouteImport.update({
  id: '/page-2/',
  path: '/page-2/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherPageIndexRoute = AnotherPageIndexRouteImport.update({
  id: '/another-page/',
  path: '/another-page/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/another-page': typeof AnotherPageIndexRoute
  '/page-2': typeof Page2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/another-page': typeof AnotherPageIndexRoute
  '/page-2': typeof Page2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/another-page/': typeof AnotherPageIndexRoute
  '/page-2/': typeof Page2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/another-page' | '/page-2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/another-page' | '/page-2'
  id: '__root__' | '/' | '/another-page/' | '/page-2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageIndexRoute: typeof AnotherPageIndexRoute
  Page2IndexRoute: typeof Page2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-2/': {
      id: '/page-2/'
      path: '/page-2'
      fullPath: '/page-2'
      preLoaderRoute: typeof Page2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/another-page/': {
      id: '/another-page/'
      path: '/another-page'
      fullPath: '/another-page'
      preLoaderRoute: typeof AnotherPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageIndexRoute: AnotherPageIndexRoute,
  Page2IndexRoute: Page2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
